import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const { GmxApiSdk, PrivateKeySigner }=require('@gmx-io/sdk/v2');
const { getContract }=require('@gmx-io/sdk/configs/contracts');
import { getAddress, isAddress, keccak256, toHex, verifyMessage, verifyTypedData, zeroHash } from 'viem';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = process.env.LOCALAPPDATA ? path.join(process.env.LOCALAPPDATA,'MylesAI') : path.join(os.homedir(),'AppData','Local','MylesAI');
const DATA_DIR = path.join(ROOT,'data');
const CONFIG_FILE = path.join(DATA_DIR,'gmx_live_config.json');
const PENDING_FILE = path.join(DATA_DIR,'gmx_live_setup_pending.json');
const STATUS_FILE = path.join(DATA_DIR,'gmx_live_status.json');
const AUTO_FILE = path.join(DATA_DIR,'gmx_live_auto_state.json');
const AUDIT_FILE = path.join(DATA_DIR,'gmx_live_audit.jsonl');
const QUANT_STATUS_FILE = path.join(DATA_DIR,'trading_status.json');
const EXEC_LOCK_FILE = path.join(DATA_DIR,'gmx_live_execution.lock');
const PENDING_ACTIONS_FILE = path.join(DATA_DIR,'gmx_live_pending_actions.json');
const VERSION='0.6.2';
const CHAIN_ID=42161;
const USDC='0xaf88d065e77c8cC2239327C5EDb3A432268e5831';
const SUBACCOUNT_MESSAGE='Generate a GMX 1CT (One-Click Trading) session. Only sign this message on a trusted website.';
const SUBACCOUNT_ORDER_ACTION=keccak256(toHex('SUBACCOUNT_ORDER_ACTION'));
const ALLOWED=['BTC/USD','ETH/USD','SOL/USD','XRP/USD','TAO/USD'];
const TERMINAL=new Set(['executed','cancelled','relay_failed','relay_reverted']);
const sdk=new GmxApiSdk({chainId:CHAIN_ID});

const iso=()=>new Date().toISOString();
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
const replacer=(_k,v)=>typeof v==='bigint'?v.toString():v;
const clean=v=>JSON.parse(JSON.stringify(v,replacer));
function readJson(file,fallback=null){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}}
function writeJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=`${file}.tmp-${process.pid}`;fs.writeFileSync(tmp,JSON.stringify(value,replacer,2),'utf8');fs.renameSync(tmp,file);}
function audit(event,detail={}){fs.mkdirSync(DATA_DIR,{recursive:true});fs.appendFileSync(AUDIT_FILE,JSON.stringify({ts:iso(),event,...detail},replacer)+'\n','utf8');}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function withExecutionLock(label,fn,timeoutMs=45000){
  fs.mkdirSync(DATA_DIR,{recursive:true});
  const start=Date.now();let fd=null;
  for(;;){
    try{fd=fs.openSync(EXEC_LOCK_FILE,'wx');fs.writeFileSync(fd,JSON.stringify({pid:process.pid,label,created_at:iso()}));break;}
    catch(e){
      if(e?.code!=='EEXIST')throw e;
      try{const st=fs.statSync(EXEC_LOCK_FILE);if(Date.now()-st.mtimeMs>120000){fs.rmSync(EXEC_LOCK_FILE,{force:true});continue;}}catch{}
      if(Date.now()-start>timeoutMs)throw new Error(`Another live GMX action is still running (${label} waited ${Math.round(timeoutMs/1000)}s).`);
      await sleep(250);
    }
  }
  try{return await fn();}
  finally{try{if(fd!==null)fs.closeSync(fd);}catch{}try{fs.rmSync(EXEC_LOCK_FILE,{force:true});}catch{}}
}
function pendingActions(){const x=readJson(PENDING_ACTIONS_FILE,[]);return Array.isArray(x)?x:[];}
function savePendingActions(rows){writeJson(PENDING_ACTIONS_FILE,rows.slice(-50));}
function addPendingAction(row){const rows=pendingActions().filter(x=>x?.request_id!==row?.request_id);rows.push({...row,created_at:iso(),created_ms:Date.now()});savePendingActions(rows);}
async function reconcilePendingActions(){const rows=pendingActions(),keep=[];for(const row of rows){if(!row?.request_id)continue;try{const st=await sdk.fetchOrderStatus({requestId:row.request_id});if(['executed','cancelled','relay_failed','relay_reverted'].includes(st?.status)){audit('pending_action_final',{...row,status:st.status});continue;}keep.push({...row,last_status:st?.status||row.last_status,last_checked_at:iso()});}catch{if(Date.now()-Number(row.created_ms||0)<10*60*1000)keep.push(row);}}savePendingActions(keep);return keep;}
async function assertNoRecentPending(action,symbol,side=''){const rows=await reconcilePendingActions();const hit=rows.find(x=>x.action===action&&x.symbol===symbol&&(!side||!x.side||x.side===side)&&Date.now()-Number(x.created_ms||0)<10*60*1000);if(hit)throw new Error(`A recent LIVE ${action} for ${symbol} is still ${hit.last_status||'pending'} (request ${hit.request_id}). Wait for it to settle before retrying.`);}
function same(a,b){try{return getAddress(a)===getAddress(b);}catch{return false;}}
function parseUnits(value,decimals){const s=String(value??'0').trim();if(!/^\d+(\.\d+)?$/.test(s))throw new Error('Invalid decimal amount');const [w,f='']=s.split('.');const frac=(f+'0'.repeat(decimals)).slice(0,decimals);return BigInt(w)*(10n**BigInt(decimals))+BigInt(frac||'0');}
function fmtUnits(value,decimals,max=6){const v=BigInt(value||0),base=10n**BigInt(decimals),w=v/base;let f=(v%base).toString().padStart(decimals,'0').slice(0,max).replace(/0+$/,'');return f?`${w}.${f}`:String(w);}
const usd30=value=>parseUnits(Number(value).toFixed(2),30);
const from30=value=>Number(fmtUnits(value,30,8));
const lev4=value=>value===undefined||value===null?null:Number(value)/10000;

function dpapi(mode,input){
  if(process.platform!=='win32')throw new Error('The live key vault requires Windows DPAPI on the Myles tower.');
  const protect=mode==='protect';
  const body=protect
    ? "$s=[Console]::In.ReadToEnd();$b=[Text.Encoding]::UTF8.GetBytes($s);$p=[Security.Cryptography.ProtectedData]::Protect($b,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser);[Console]::Out.Write([Convert]::ToBase64String($p))"
    : "$s=[Console]::In.ReadToEnd().Trim();$b=[Convert]::FromBase64String($s);$p=[Security.Cryptography.ProtectedData]::Unprotect($b,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser);[Console]::Out.Write([Text.Encoding]::UTF8.GetString($p))";
  const r=spawnSync('powershell.exe',['-NoLogo','-NoProfile','-NonInteractive','-Command',`$ErrorActionPreference='Stop';${body}`],{input,encoding:'utf8',windowsHide:true,maxBuffer:1024*1024});
  if(r.status!==0)throw new Error(`Windows key vault ${mode} failed: ${String(r.stderr||'').trim()}`);
  return String(r.stdout||'').trim();
}

function defaults(){return{schema_version:1,version:VERSION,chain_id:CHAIN_ID,venue:'GMX',setup_complete:false,main_account:null,subaccount_address:null,encrypted_subaccount_key:null,signed_approval:null,approval_pending_request_id:null,armed:false,armed_until:0,auto_enabled:false,owner_auth_nonce:0,allowed_symbols:[...ALLOWED],risk:{max_margin_usd:100,max_order_notional_usd:250,max_leverage:2,max_open_positions:2,min_stop_loss_pct:.35,max_stop_loss_pct:5,max_take_profit_pct:12,auto_margin_usd:25,auto_leverage:1.5,auto_stop_loss_pct:.75,auto_take_profit_pct:1.25}};}
function loadConfig(){const d=defaults(),r=readJson(CONFIG_FILE,{});return{...d,...r,risk:{...d.risk,...(r.risk||{})},chain_id:CHAIN_ID,venue:'GMX',allowed_symbols:ALLOWED.filter(s=>(r.allowed_symbols||ALLOWED).includes(s)),armed:!!r.armed,auto_enabled:!!r.auto_enabled};}
function saveConfig(c){c.version=VERSION;c.updated_at=iso();writeJson(CONFIG_FILE,c);}
function armedNow(c){return !!c.armed&&Number(c.armed_until||0)>Math.floor(Date.now()/1000);}
function expireArmIfNeeded(c){if(c.armed&&!armedNow(c)){c.armed=false;c.auto_enabled=false;c.armed_until=0;saveConfig(c);audit('live_session_expired');return true;}return false;}
function assertArmed(c){expireArmIfNeeded(c);if(!armedNow(c))throw new Error('Live execution is not armed. Arm an 8-hour live session from Funding.');}
function serializeApproval(a){return a?{subaccount:a.subaccount,shouldAdd:!!a.shouldAdd,expiresAt:String(a.expiresAt),maxAllowedCount:String(a.maxAllowedCount),actionType:a.actionType,nonce:String(a.nonce),desChainId:String(a.desChainId),deadline:String(a.deadline),integrationId:a.integrationId,signature:a.signature,signedAt:Number(a.signedAt||Date.now()),signatureChainId:Number(a.signatureChainId||CHAIN_ID),subaccountRouterAddress:a.subaccountRouterAddress}:null;}
function hydrateApproval(a){return a?{subaccount:a.subaccount,shouldAdd:!!a.shouldAdd,expiresAt:BigInt(a.expiresAt||0),maxAllowedCount:BigInt(a.maxAllowedCount||0),actionType:a.actionType,nonce:BigInt(a.nonce||0),desChainId:BigInt(a.desChainId||CHAIN_ID),deadline:BigInt(a.deadline||0),integrationId:a.integrationId||zeroHash,signature:a.signature||'0x',signedAt:Number(a.signedAt||0),signatureChainId:Number(a.signatureChainId||CHAIN_ID),subaccountRouterAddress:a.subaccountRouterAddress}:null;}
function emptyApproval(sub){return{subaccount:sub,shouldAdd:true,expiresAt:0n,maxAllowedCount:0n,actionType:SUBACCOUNT_ORDER_ACTION,nonce:0n,desChainId:BigInt(CHAIN_ID),deadline:0n,integrationId:zeroHash,signature:'0x'};}

async function fullSymbol(short){
  if(!ALLOWED.includes(short))throw new Error('Unsupported live market');
  const rows=await sdk.fetchMarkets();
  const candidates=(rows||[]).filter(m=>{const name=String(m?.name||m?.symbol||'');return name.startsWith(short)&&m?.isDisabled!==true&&m?.disabled!==true&&m?.isListed!==false;});
  const chosen=candidates.find(m=>String(m?.name||m?.symbol||'').includes('USDC'))||candidates[0];
  const name=String(chosen?.name||chosen?.symbol||'');if(!name)throw new Error(`No active GMX market for ${short}`);return name;
}
async function subStatus(c){if(!c.main_account||!c.subaccount_address)return null;try{return await sdk.fetchSubaccountStatus({account:c.main_account,subaccountAddress:c.subaccount_address});}catch(e){return{active:false,error:String(e?.message||e)};}}
async function balances(c){if(!c.main_account)return[];try{return await sdk.fetchWalletBalances({address:c.main_account});}catch(e){return[{error:String(e?.message||e)}];}}
async function allowances(c){if(!c.main_account)return[];try{return await sdk.fetchAllowances({address:c.main_account,spender:'router'});}catch(e){return[{error:String(e?.message||e)}];}}
async function positions(c){if(!c.main_account)return[];try{return await sdk.fetchPositionsInfo({address:c.main_account,includeRelatedOrders:true});}catch(e){return[{error:String(e?.message||e)}];}}
async function orders(c){if(!c.main_account)return[];try{return await sdk.fetchOrders({address:c.main_account});}catch(e){return[{error:String(e?.message||e)}];}}
function usdcRow(rows){return(rows||[]).find(x=>String(x?.symbol||'').toUpperCase()==='USDC'||same(x?.address,USDC));}
function setupReady(c,s){if(!c.setup_complete||!c.encrypted_subaccount_key||!c.subaccount_address)return false;if(s?.active&&BigInt(s.remainingActions||0)>0n&&BigInt(s.expiresAt||0)>BigInt(Math.floor(Date.now()/1000)))return true;return !!c.signed_approval?.signature&&c.signed_approval.signature!=='0x';}
function normalizePosition(p){
  if(p?.error)return p;
  const name=String(p?.indexName||p?.market?.name||p?.marketName||p?.poolName||'');
  const symbol=ALLOWED.find(s=>name.startsWith(s))||name.split(' [')[0]||'—';
  const related=Array.isArray(p.relatedOrders)?p.relatedOrders:[],sl=related.find(o=>Number(o?.orderType)===6),tp=related.find(o=>Number(o?.orderType)===5);
  return{key:p.key||p.contractKey||'',symbol,full_symbol:name,side:p.isLong?'long':'short',size_usd:from30(p.sizeInUsd||0),collateral_usd:from30(p.collateralUsd||p.remainingCollateralUsd||0),entry_price:p.entryPrice?from30(p.entryPrice):null,mark_price:p.markPrice?from30(p.markPrice):null,unrealized_pnl:from30(p.pnlAfterAllFees??p.pnlAfterFees??p.pnl??0),leverage:lev4(p.leverage),liquidation_price:p.liquidationPrice?from30(p.liquidationPrice):null,stop_loss:sl?.triggerPrice?from30(sl.triggerPrice):null,take_profit:tp?.triggerPrice?from30(tp.triggerPrice):null,raw_size_usd:String(p.sizeInUsd||0)};
}
const ORDER_TYPE_NAMES={0:'market-swap',1:'limit-swap',2:'market-increase',3:'limit-increase',4:'market-decrease',5:'take-profit',6:'stop-loss',7:'liquidation',8:'stop-increase'};
function normalizeOrder(o,marketNames={}){
  if(o?.error)return o;
  const market=marketNames[String(o.marketAddress||'').toLowerCase()]||o.indexName||o.marketName||o.marketAddress||'';
  return{key:o.key||o.orderKey||o.id||'',type:ORDER_TYPE_NAMES[Number(o.orderType)]||o.orderType||o.type||'',side:o.isLong===true?'long':o.isLong===false?'short':o.direction||'',status:o.status||'open',market,trigger_price:o.triggerPrice?from30(o.triggerPrice):null,size_usd:o.sizeDeltaUsd?from30(o.sizeDeltaUsd):null};
}

async function publicStatus(){const tick=await sdk.fetchMarketsTickers({symbols:['BTC/USD','ETH/USD']});return{ok:true,version:VERSION,chain_id:CHAIN_ID,market_probe:clean((tick||[]).slice(0,2))};}
async function status(){
  const c=loadConfig();expireArmIfNeeded(c);const[s,b,a,p,o,m]=await Promise.all([subStatus(c),balances(c),allowances(c),positions(c),orders(c),sdk.fetchMarkets().catch(()=>[])]);const ub=usdcRow(b),ua=usdcRow(a),marketNames={};
  for(const row of m||[]){if(row?.marketTokenAddress)marketNames[String(row.marketTokenAddress).toLowerCase()]=String(row.symbol||row.name||row.marketTokenAddress);}
  const out={ok:true,version:VERSION,generated_at:iso(),chain_id:CHAIN_ID,venue:'GMX',mode:'one_click_subaccount',setup_complete:!!c.setup_complete,main_account:c.main_account,subaccount_address:c.subaccount_address,armed:armedNow(c),armed_until:Number(c.armed_until||0),auto_enabled:armedNow(c)&&!!c.auto_enabled,owner_auth_nonce:Number(c.owner_auth_nonce||0),signing_ready:setupReady(c,s),withdrawal_delegated:false,safety_note:'Trading is delegated to a GMX one-click subaccount. Withdrawals always require the owner wallet signature.',subaccount_status:clean(s),usdc:{address:USDC,balance_raw:ub?.balance?.toString?.()??'0',balance:ub?.balance!==undefined?fmtUnits(ub.balance,Number(ub.decimals||6),6):'0',router_allowance_raw:ua?.allowance?.toString?.()??'0',router_allowance:ua?.allowance!==undefined?fmtUnits(ua.allowance,Number(ua.decimals||6),6):'0'},positions:(p||[]).map(normalizePosition),orders:(o||[]).map(x=>normalizeOrder(x,marketNames)),risk:c.risk,allowed_symbols:c.allowed_symbols};writeJson(STATUS_FILE,out);return out;
}

async function setupBegin(p){
  const account=String(p?.account||'').trim(),sig=String(p?.derivation_signature||'').trim();if(!isAddress(account))throw new Error('Invalid owner wallet address');if(!/^0x[0-9a-fA-F]+$/.test(sig))throw new Error('Missing GMX one-click derivation signature');
  if(!await verifyMessage({address:account,message:SUBACCOUNT_MESSAGE,signature:sig}))throw new Error('Derivation signature does not match the connected owner wallet');
  const pk=keccak256(sig),signer=new PrivateKeySigner(pk),sub=signer.address;const existing=await sdk.fetchSubaccountStatus({account,subaccountAddress:sub}).catch(()=>null);const hours=Math.round(clamp(n(p?.expires_hours,72),1,168)),count=Math.round(clamp(n(p?.max_actions,100),5,500)),now=Math.floor(Date.now()/1000),expiresAt=Math.max(now+hours*3600,Number(existing?.expiresAt||0)),maxAllowed=Math.max(count,Number(existing?.currentActionsCount||0)+count);const usable=existing?.active===true&&Number(existing?.remainingActions||0)>0&&Number(existing?.expiresAt||0)>now&&Number(existing?.maxAllowedCount||0)>=maxAllowed;let prepared=null;if(!usable)prepared=await sdk.prepareSubaccountApproval({account,subaccountAddress:sub,shouldAdd:existing?.active!==true,expiresAt:String(expiresAt),maxAllowedCount:String(maxAllowed)});
  const pending={version:VERSION,created_at:iso(),account:getAddress(account),subaccount_address:getAddress(sub),encrypted_subaccount_key:dpapi('protect',pk),prepared:clean(prepared),existing_status:clean(existing)};writeJson(PENDING_FILE,pending);
  if(usable){const c=loadConfig();Object.assign(c,{setup_complete:true,main_account:getAddress(account),subaccount_address:getAddress(sub),encrypted_subaccount_key:pending.encrypted_subaccount_key,signed_approval:null,approval_pending_request_id:null,armed:false,auto_enabled:false});saveConfig(c);fs.rmSync(PENDING_FILE,{force:true});audit('setup_reused',{account:c.main_account,subaccount:c.subaccount_address});return{ok:true,needs_approval:false,setup_complete:true,account:c.main_account,subaccount_address:c.subaccount_address,status:clean(existing)};}
  audit('setup_begin',{account:getAddress(account),subaccount:getAddress(sub),expiresAt,maxAllowed});return{ok:true,needs_approval:true,setup_complete:false,account:getAddress(account),subaccount_address:getAddress(sub),sign_typed_data:{domain:prepared.domain,types:prepared.types,primaryType:prepared.primaryType,message:prepared.message}};
}
function validateApprovalPrepared(q,x){if(q?.domain?.name!=='GmxBaseGelatoRelayRouter'||String(q?.domain?.version)!=='1'||Number(q?.domain?.chainId)!==CHAIN_ID)throw new Error('GMX approval typed-data domain validation failed');const verifying=q?.domain?.verifyingContract?getAddress(q.domain.verifyingContract):null;if(!verifying||!knownRelayRouters().has(verifying))throw new Error('GMX approval verifying contract is not a known relay router');if(!same(q.message?.subaccount,x.subaccount_address))throw new Error('Approval subaccount mismatch');if(q.message?.account&&!same(q.message.account,x.account))throw new Error('Approval account mismatch');if(String(q.message?.actionType||'').toLowerCase()!==SUBACCOUNT_ORDER_ACTION.toLowerCase())throw new Error('GMX approval action type is not trading-only');if(Number(q.message?.desChainId||CHAIN_ID)!==CHAIN_ID)throw new Error('GMX approval destination chain mismatch');}
async function setupFinish(p){
  const x=readJson(PENDING_FILE,null);if(!x?.prepared)throw new Error('No pending GMX setup. Start setup again.');const sig=String(p?.approval_signature||'').trim();if(!/^0x[0-9a-fA-F]+$/.test(sig))throw new Error('Missing approval signature');const q=x.prepared;validateApprovalPrepared(q,x);if(!await verifyTypedData({address:x.account,domain:q.domain,types:q.types,primaryType:q.primaryType,message:q.message,signature:sig}))throw new Error('Approval signature does not match the owner wallet');const approval=serializeApproval({subaccount:q.message.subaccount,shouldAdd:Boolean(q.message.shouldAdd),expiresAt:BigInt(q.message.expiresAt||0),maxAllowedCount:BigInt(q.message.maxAllowedCount||0),actionType:q.message.actionType,nonce:BigInt(q.message.nonce??q.nonce??0),desChainId:BigInt(q.message.desChainId||CHAIN_ID),deadline:BigInt(q.message.deadline||0),integrationId:q.message.integrationId||zeroHash,signature:sig,signedAt:Date.now(),signatureChainId:Number(q.domain.chainId||CHAIN_ID),subaccountRouterAddress:q.relayRouterAddress});const c=loadConfig();Object.assign(c,{setup_complete:true,main_account:getAddress(x.account),subaccount_address:getAddress(x.subaccount_address),encrypted_subaccount_key:x.encrypted_subaccount_key,signed_approval:approval,approval_pending_request_id:null,armed:false,auto_enabled:false});saveConfig(c);fs.rmSync(PENDING_FILE,{force:true});audit('setup_finish',{account:c.main_account,subaccount:c.subaccount_address});return{ok:true,setup_complete:true,account:c.main_account,subaccount_address:c.subaccount_address,armed:false};
}

async function approvalFor(c){const s=await subStatus(c),now=Math.floor(Date.now()/1000);if(s?.active&&Number(s.remainingActions||0)>0&&Number(s.expiresAt||0)>now){if(c.signed_approval||c.approval_pending_request_id){c.signed_approval=null;c.approval_pending_request_id=null;saveConfig(c);}return emptyApproval(c.subaccount_address);}if(c.approval_pending_request_id)throw new Error(`GMX one-click authorization is still activating in request ${c.approval_pending_request_id}. Wait a few seconds and retry.`);const a=hydrateApproval(c.signed_approval);if(!a?.signature||a.signature==='0x')throw new Error('GMX one-click authorization is not active. Re-run wallet setup.');if(Number(a.expiresAt||0)<=now||Number(a.deadline||0)<=now)throw new Error('GMX one-click authorization expired. Re-authorize the wallet.');return a;}
function knownRelayRouters(){const names=['GelatoRelayRouter','SubaccountGelatoRelayRouter','MultichainOrderRouter','MultichainSubaccountRouter','MultichainClaimsRouter','MultichainGlvRouter','MultichainGmRouter','MultichainTransferRouter'],out=new Set();for(const name of names){try{const a=getContract(CHAIN_ID,name);if(a)out.add(getAddress(a));}catch{}}return out;}
function validateTyped(prepared,c,subSigner){const td=prepared?.payload?.typedData;if(prepared?.payloadType!=='typed-data'||!td)throw new Error('GMX returned an invalid express-order payload');if(td.domain?.name!=='GmxBaseGelatoRelayRouter'||String(td.domain?.version)!=='1'||Number(td.domain?.chainId)!==CHAIN_ID)throw new Error('GMX typed-data domain validation failed');const verifying=td.domain?.verifyingContract?getAddress(td.domain.verifyingContract):null;if(!verifying||!knownRelayRouters().has(verifying))throw new Error('GMX typed-data verifying contract is not a known relay router');const owner=getAddress(c.main_account),delegated=getAddress(subSigner),zero='0x0000000000000000000000000000000000000000',allowed=new Set([owner,delegated,zero]);if(td.message?.account){const a=getAddress(td.message.account);if(!allowed.has(a))throw new Error('GMX typed-data account is not the owner/delegated signer');}for(const order of td.message?.createOrderParamsList||[]){const receiver=order?.addresses?.receiver;if(receiver){const a=getAddress(receiver);if(!allowed.has(a))throw new Error('GMX order receiver is not the owner/delegated signer');}const cancel=order?.addresses?.cancellationReceiver;if(cancel){const a=getAddress(cancel);if(!allowed.has(a))throw new Error('GMX cancellation receiver is not the owner/delegated signer');}}return td;}
async function signSubmit(c,prepareFn){const signer=new PrivateKeySigner(dpapi('unprotect',c.encrypted_subaccount_key));if(!same(signer.address,c.subaccount_address))throw new Error('Encrypted subaccount key mismatch');const approval=await approvalFor(c),prepared=await prepareFn(approval),td=validateTyped(prepared,c,signer.address),signature=await signer.signTypedData(td.domain,td.types,td.message),submitted=await sdk.submitOrder({mode:prepared.mode,requestId:prepared.requestId,signature,from:c.main_account,idempotencyKey:prepared.idempotencyKey,eip712Data:{batchParams:prepared.payload.batchParams,relayParams:prepared.payload.relayParams,subaccountApproval:approval}});if(approval?.signature&&approval.signature!=='0x'){c.approval_pending_request_id=submitted.requestId||prepared.requestId;saveConfig(c);for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,1500));const st=await subStatus(c);if(st?.active&&Number(st.remainingActions||0)>0){c.signed_approval=null;c.approval_pending_request_id=null;saveConfig(c);break;}}}return{approval,prepared,submitted};}
async function waitOrder(id,timeout=60000){const t=Date.now();while(Date.now()-t<timeout){const s=await sdk.fetchOrderStatus({requestId:id});if(TERMINAL.has(s.status)||s.status==='created')return clean(s);await new Promise(r=>setTimeout(r,2000));}return clean(await sdk.fetchOrderStatus({requestId:id}));}
function validateOpen(c,p){const symbol=String(p?.symbol||'').toUpperCase(),side=String(p?.side||'').toLowerCase(),margin=n(p?.margin_usd),leverage=n(p?.leverage,1),stop=n(p?.stop_loss_pct),take=n(p?.take_profit_pct);if(!c.allowed_symbols.includes(symbol))throw new Error('Market is not allowed');if(!['long','short'].includes(side))throw new Error('Side must be long or short');if(margin<=0||margin>c.risk.max_margin_usd)throw new Error(`Live margin must be $0-$${c.risk.max_margin_usd}`);if(leverage<1||leverage>c.risk.max_leverage)throw new Error(`Live leverage max is ${c.risk.max_leverage}x`);const notional=margin*leverage;if(notional>c.risk.max_order_notional_usd)throw new Error(`Live notional max is $${c.risk.max_order_notional_usd}`);if(stop<c.risk.min_stop_loss_pct||stop>c.risk.max_stop_loss_pct)throw new Error('Stop-loss is outside owner live-risk limits');if(take<=0||take>c.risk.max_take_profit_pct)throw new Error('Take-profit is outside owner live-risk limits');return{symbol,side,margin,leverage,stop,take,notional};}
async function openOrder(p){const c=loadConfig();if(!c.setup_complete)throw new Error('Set up the owner wallet first');assertArmed(c);const r=validateOpen(c,p);await assertNoRecentPending('open',r.symbol,r.side);const pos=(await positions(c)).filter(x=>!x?.error);if(pos.length>=c.risk.max_open_positions)throw new Error('Maximum live position count reached');if(pos.some(x=>String(x?.indexName||'').startsWith(r.symbol)))throw new Error(`${r.symbol} already has a live position`);const full=await fullSymbol(r.symbol),ticker=(await sdk.fetchMarketsTickers({symbols:[full]}))[0];if(!ticker)throw new Error(`No live GMX ticker for ${full}`);const mark=BigInt(r.side==='long'?ticker.maxPrice:ticker.minPrice),size=usd30(r.notional),collateral=parseUnits(r.margin.toFixed(6),6),ub=usdcRow(await balances(c)),ua=usdcRow(await allowances(c));if(!ub||BigInt(ub.balance||0)<collateral)throw new Error('Owner wallet USDC balance is below the requested margin');if(!ua||BigInt(ua.allowance||0)<collateral)throw new Error('Approve USDC for GMX on the Funding page before opening a live position');const factor=x=>BigInt(Math.round(x*10000));const stop=r.side==='long'?mark*factor(100-r.stop)/1000000n:mark*factor(100+r.stop)/1000000n,take=r.side==='long'?mark*factor(100+r.take)/1000000n:mark*factor(100-r.take)/1000000n;const request={kind:'increase',symbol:full,direction:r.side,orderType:'market',size,collateralToken:'USDC',collateralToPay:{amount:collateral,token:'USDC'},mode:'express',from:c.main_account,tpsl:[{type:'take-profit',triggerPrice:take,size},{type:'stop-loss',triggerPrice:stop,size}]};const res=await signSubmit(c,a=>sdk.prepareOrder({...request,subaccountAddress:c.subaccount_address,subaccountApproval:a}));addPendingAction({action:'open',symbol:r.symbol,side:r.side,request_id:res.submitted.requestId,last_status:res.submitted.status});const final=await waitOrder(res.submitted.requestId);await reconcilePendingActions();audit('order_open',{symbol:r.symbol,side:r.side,requestId:res.submitted.requestId,status:final.status});if(!['created','executed'].includes(final.status))throw new Error(`GMX order ${final.status}: ${final?.error?.message||final?.cancellationReason||'unknown error'}`);return{ok:true,action:'open',symbol:r.symbol,full_symbol:full,status:final,submitted:clean(res.submitted)};}
async function closeOne(c,p){const name=String(p?.indexName||p?.market?.name||p?.marketName||''),short=ALLOWED.find(s=>name.startsWith(s))||String(name).split(' [')[0],full=String(p?.market?.name||p?.marketName||p?.fullMarket||'')||await fullSymbol(short),direction=p.isLong===true?'long':'short',size=BigInt(p.sizeInUsd||0);if(size<=0n)throw new Error(`Position size unavailable for ${short}`);await assertNoRecentPending('close',short,direction);const request={kind:'decrease',symbol:full,direction,orderType:'market',size,collateralToken:'USDC',receiveToken:'USDC',mode:'express',from:c.main_account};const res=await signSubmit(c,a=>sdk.prepareOrder({...request,subaccountAddress:c.subaccount_address,subaccountApproval:a}));addPendingAction({action:'close',symbol:short,side:direction,request_id:res.submitted.requestId,last_status:res.submitted.status});const final=await waitOrder(res.submitted.requestId);await reconcilePendingActions();audit('order_close',{symbol:short,side:direction,requestId:res.submitted.requestId,status:final.status});if(!['created','executed'].includes(final.status))throw new Error(`GMX close ${final.status}: ${final?.error?.message||final?.cancellationReason||'unknown error'}`);return{ok:true,action:'close',symbol:short,status:final,submitted:clean(res.submitted)};}
async function closeOrder(p){const c=loadConfig();if(!c.setup_complete)throw new Error('Set up the owner wallet first');assertArmed(c);const short=String(p?.symbol||'').toUpperCase(),side=String(p?.side||'').toLowerCase(),rows=await positions(c),pos=rows.find(x=>String(x?.indexName||'').startsWith(short)&&(!side||(x.isLong===true?'long':'short')===side));if(!pos)throw new Error(`No live ${short} position`);return closeOne(c,pos);}
async function closeAll(){const c=loadConfig();if(!c.setup_complete)throw new Error('Set up the owner wallet first');assertArmed(c);const rows=(await positions(c)).filter(x=>!x?.error),results=[];for(const p of rows){try{results.push(await closeOne(c,p));}catch(e){results.push({ok:false,error:String(e?.message||e)});}}return{ok:true,action:'close_all',results};}
async function cancel(p){const c=loadConfig();if(!c.setup_complete)throw new Error('Set up the owner wallet first');assertArmed(c);const req={mode:'express',from:c.main_account,subaccountAddress:c.subaccount_address};if(p?.all)req.all=true;else if(p?.order_id)req.orderId=String(p.order_id);else throw new Error('order_id or all=true required');const res=await signSubmit(c,a=>sdk.prepareCancelOrder({...req,subaccountApproval:a}));const final=await waitOrder(res.submitted.requestId);audit('order_cancel',{all:!!p?.all,orderId:p?.order_id||null,status:final.status});return{ok:true,action:'cancel',status:final,submitted:clean(res.submitted)};}
async function orderAction(p){const c=loadConfig();if(!c.setup_complete)throw new Error('Set up the owner wallet first');assertArmed(c);const a=String(p?.action||'').toLowerCase();if(a==='open')return openOrder(p);if(a==='close')return closeOrder(p);if(a==='close_all')return closeAll();if(a==='cancel')return cancel(p);if(a==='cancel_all')return cancel({all:true});throw new Error('Unknown live order action');}

function canonicalRisk(r){if(!r||typeof r!=='object')return'';const f=(v,d)=>n(v,0).toFixed(d);return `max_margin=${f(r.max_margin_usd,2)},max_notional=${f(r.max_order_notional_usd,2)},max_leverage=${f(r.max_leverage,2)},max_positions=${Math.round(n(r.max_open_positions,0))},auto_margin=${f(r.auto_margin_usd,2)},auto_leverage=${f(r.auto_leverage,2)},auto_stop=${f(r.auto_stop_loss_pct,4)},auto_take=${f(r.auto_take_profit_pct,4)}`;}
function armMessage(c,armed,auto,risk=null){const suffix=risk?` | risk=${canonicalRisk(risk)}`:'';return `Myles GMX live authorization | chain=${CHAIN_ID} | account=${getAddress(c.main_account)} | armed=${armed?1:0} | auto=${auto?1:0} | nonce=${Number(c.owner_auth_nonce||0)}${suffix}`;}
async function requireOwnerAuthorization(c,p,armed,auto){const sig=String(p?.owner_signature||'');if(!sig)throw new Error('Owner wallet signature is required for arming, live Auto, or live-risk changes');const msg=armMessage(c,armed,auto,p?.risk||null);if(!await verifyMessage({address:c.main_account,message:msg,signature:sig}))throw new Error('Owner live-authorization signature is invalid');return msg;}
async function arm(p){const c=loadConfig();if(!c.setup_complete)throw new Error('GMX one-click setup is incomplete');expireArmIfNeeded(c);const requested=!!p?.armed,auto=p?.auto_enabled===undefined?(requested?!!c.auto_enabled:false):!!p.auto_enabled;if(requested||auto||p?.risk){await requireOwnerAuthorization(c,p,requested,auto);}if(p?.risk){const r=p.risk;c.risk.max_margin_usd=clamp(n(r.max_margin_usd,c.risk.max_margin_usd),5,10000);c.risk.max_order_notional_usd=clamp(n(r.max_order_notional_usd,c.risk.max_order_notional_usd),10,50000);c.risk.max_leverage=clamp(n(r.max_leverage,c.risk.max_leverage),1,10);c.risk.max_open_positions=Math.round(clamp(n(r.max_open_positions,c.risk.max_open_positions),1,5));c.risk.auto_margin_usd=clamp(n(r.auto_margin_usd,c.risk.auto_margin_usd),5,c.risk.max_margin_usd);c.risk.auto_leverage=clamp(n(r.auto_leverage,c.risk.auto_leverage),1,c.risk.max_leverage);c.risk.auto_stop_loss_pct=clamp(n(r.auto_stop_loss_pct,c.risk.auto_stop_loss_pct),c.risk.min_stop_loss_pct,c.risk.max_stop_loss_pct);c.risk.auto_take_profit_pct=clamp(n(r.auto_take_profit_pct,c.risk.auto_take_profit_pct),0.25,c.risk.max_take_profit_pct);}if(requested){const st=await subStatus(c);if(!setupReady(c,st))throw new Error('GMX one-click authorization is not ready');const ub=usdcRow(await balances(c));if(!ub||BigInt(ub.balance||0)<=0n)throw new Error('Owner wallet has no USDC on Arbitrum');const now=Math.floor(Date.now()/1000);if(!armedNow(c))c.armed_until=now+8*3600;c.armed=true;c.auto_enabled=!!auto;}else{c.armed=false;c.auto_enabled=false;c.armed_until=0;}c.owner_auth_nonce=Number(c.owner_auth_nonce||0)+1;saveConfig(c);audit(requested?'live_armed':'live_disarmed',{auto_enabled:c.auto_enabled,armed_until:c.armed_until,risk:c.risk,owner_authorized:requested||auto});return{ok:true,armed:armedNow(c),armed_until:c.armed_until,auto_enabled:armedNow(c)&&c.auto_enabled,risk:c.risk,owner_auth_nonce:c.owner_auth_nonce};}

async function buildApprove(){const c=loadConfig();if(!c.main_account)throw new Error('Connect/setup owner wallet first');const tx=sdk.buildApproveTransaction({tokenAddress:USDC,spender:'router'});return{ok:true,kind:'approve_usdc',owner_signature_required:true,tx:{from:c.main_account,to:tx.to,data:tx.data,value:`0x${tx.value.toString(16)}`}};}
function encodeTransfer(to,amount){if(!isAddress(to))throw new Error('Invalid withdrawal destination');const raw=parseUnits(Number(amount).toFixed(6),6);if(raw<=0n)throw new Error('Withdrawal amount must be positive');return{to:USDC,data:`0xa9059cbb${getAddress(to).slice(2).toLowerCase().padStart(64,'0')}${raw.toString(16).padStart(64,'0')}`,value:'0x0',amount_raw:raw.toString()};}
async function buildWithdraw(p){const c=loadConfig();if(!c.main_account)throw new Error('Connect/setup owner wallet first');const tx=encodeTransfer(p?.to,p?.amount_usdc);audit('withdraw_prepared',{to:getAddress(p.to),amount_usdc:String(p.amount_usdc)});return{ok:true,kind:'owner_wallet_usdc_transfer',owner_signature_required:true,tx:{from:c.main_account,...tx}};}

async function autoCycle(){const c=loadConfig();expireArmIfNeeded(c);if(!c.setup_complete||!armedNow(c)||!c.auto_enabled)return{ok:true,skipped:true,reason:'live_auto_disabled'};const q=readJson(QUANT_STATUS_FILE,null);if(!Array.isArray(q?.signals))return{ok:true,skipped:true,reason:'no_quant_signals'};const st=readJson(AUTO_FILE,{last_candle_ts:{}});st.last_candle_ts=st.last_candle_ts||{};let current=(await positions(c)).filter(x=>!x?.error),actions=[];for(const sig of q.signals){const symbol=String(sig.symbol||'');if(!c.allowed_symbols.includes(symbol))continue;if(sig.validation_pass!==true){audit('auto_signal_skipped_unvalidated',{symbol,strategy:String(sig.strategy||''),signal:String(sig.signal||'')});continue;}const ts=Number(sig.candle_ts||0);if(ts<=Number(st.last_candle_ts[symbol]||0))continue;st.last_candle_ts[symbol]=ts;const signal=String(sig.signal||'flat'),p=current.find(x=>String(x.indexName||'').startsWith(symbol)),side=p?(p.isLong?'long':'short'):null;try{if(p&&(signal==='flat'||(['long','short'].includes(signal)&&signal!==side))){actions.push(await closeOne(c,p));current=current.filter(x=>x!==p);}if(!p&&['long','short'].includes(signal)){actions.push(await openOrder({symbol,side:signal,margin_usd:c.risk.auto_margin_usd,leverage:c.risk.auto_leverage,stop_loss_pct:c.risk.auto_stop_loss_pct,take_profit_pct:c.risk.auto_take_profit_pct,source:'auto'}));}}catch(e){actions.push({ok:false,symbol,error:String(e?.message||e)});audit('auto_error',{symbol,error:String(e?.message||e)});}}writeJson(AUTO_FILE,st);return{ok:true,actions};}

function selfTest(){const d=defaults(),checks={usd30:usd30(12.34)===12340000000000000000000000000000n,usdc:parseUnits('12.345678',6)===12345678n,action_hash:/^0x[0-9a-f]{64}$/i.test(SUBACCOUNT_ORDER_ACTION),withdraw_not_delegated:true,fail_closed_session:armedNow(d)===false,execution_lock_path:EXEC_LOCK_FILE.endsWith('gmx_live_execution.lock'),pending_journal_path:PENDING_ACTIONS_FILE.endsWith('gmx_live_pending_actions.json')};try{validateOpen(d,{symbol:'BTC/USD',side:'long',margin_usd:25,leverage:1.5,stop_loss_pct:.75,take_profit_pct:1.25});checks.risk_accept=true;}catch{checks.risk_accept=false;}try{validateOpen(d,{symbol:'BTC/USD',side:'long',margin_usd:9999,leverage:9,stop_loss_pct:.75,take_profit_pct:1.25});checks.risk_reject=false;}catch{checks.risk_reject=true;}return{pass:Object.values(checks).every(Boolean),checks,version:VERSION};}

async function main(){const args=process.argv.slice(2),payload=flag=>{const i=args.indexOf(flag);return i>=0?JSON.parse(args[i+1]||'{}'):null;};try{if(args.includes('--self-test')){const r=selfTest();console.log(JSON.stringify(r,null,2));process.exit(r.pass?0:1);}if(args.includes('--public-status')){console.log(JSON.stringify(await publicStatus(),replacer));return;}if(args.includes('--status')){console.log(JSON.stringify(await status(),replacer));return;}let p;if((p=payload('--setup-begin'))!==null){console.log(JSON.stringify(await withExecutionLock('setup-begin',()=>setupBegin(p)),replacer));return;}if((p=payload('--setup-finish'))!==null){console.log(JSON.stringify(await withExecutionLock('setup-finish',()=>setupFinish(p)),replacer));return;}if((p=payload('--arm'))!==null){console.log(JSON.stringify(await withExecutionLock('arm',()=>arm(p)),replacer));return;}if((p=payload('--order'))!==null){console.log(JSON.stringify(await withExecutionLock('order',()=>orderAction(p)),replacer));return;}if(args.includes('--build-approve')){console.log(JSON.stringify(await buildApprove(),replacer));return;}if((p=payload('--build-withdraw'))!==null){console.log(JSON.stringify(await buildWithdraw(p),replacer));return;}if(args.includes('--auto-cycle')){console.log(JSON.stringify(await withExecutionLock('auto-cycle',()=>autoCycle()),replacer));return;}if(args.includes('--daemon')){const boot=loadConfig();if(boot.armed||boot.auto_enabled||Number(boot.armed_until||0)>0){boot.armed=false;boot.auto_enabled=false;boot.armed_until=0;saveConfig(boot);audit('daemon_start_fail_closed_disarm');}for(;;){try{await status();await withExecutionLock('daemon-auto-cycle',()=>autoCycle(),5000);}catch(e){audit('daemon_error',{error:String(e?.message||e)});writeJson(STATUS_FILE,{ok:false,version:VERSION,generated_at:iso(),error:String(e?.message||e)});}await new Promise(r=>setTimeout(r,15000));}}console.log(JSON.stringify({ok:true,version:VERSION}));}catch(e){console.error(JSON.stringify({ok:false,error:String(e?.message||e)}));process.exit(2);}}
main();
